### PR TITLE
Fallback on response.rawRequest.header.Authorization for old browsers

### PR DESCRIPTION
**Pull request by lgiraudel**
Duplicate with #50 but for version 0.5.0.

It seems my `grunt dist` command has made many changes in the dist/stormpath.js file...

### CODE REVIEW

**Comment by robertjd** [comment]
Thank you you for this PR.  I can confirm that with Firefox 20 the Authorization header is not read.  However this proposed change won't work:
```
var newToken = response.headers.authorization || response.rawRequest.headers.Authorization;
```

This is because `response.rawRequest.headers.Authorization` is referencing the header of the request, not the response.  We have to read the header of the response, as this header contains the new authorization token that must be used to authenticate the next request.

I will continue looking at this issue with Firefox 20 to see if there is a solution for reading the Authorization header, but I will close this PR as it does not solve the issue.

**Comment by lgiraudel** [comment]
Good point.
I checked on the `xhr` modules to see if the fix can be done there but I'm not sure it's possible : it seems there is no work around to retrieve all headers when this bug happens, we can only retrieve a specific one ("Authentication" here).

**Comment by robertjd** [comment]
Hey again, I was able to figure this one out!  I just published the fix as 0.5.2, can you update to this version and confirm that the problem with Firefox < 21 is solved?  The solution was to use `xmlHttpRequest.getResponseHeader()` to ask for a specific header, in stead of relying on all headers to be pulled from `xmlHttpRequest.getAllResponseHeaders()`.  Thanks for finding this bug for us!

**Comment by lgiraudel** [comment]
Hello @robertjd, thanks for the quick fix.

I tried the 0.5.2 version, unfortunately I think it breaks the login process (and maybe other actions).

With chrome, I have the following error `Refused to get unsafe header "Authorization"` and the referenced line seems to be your commit:
```
g = b.headers.authorization || b.rawRequest.getResponseHeader && b.rawRequest.getResponseHeader("Authorization")
```

Screenshot

**Comment by lgiraudel** [comment]
I tried to use the 0.5.1 version for now, unfortunately our ID Site angular app has forked from yours and will require to be upgraded to be able to use the 0.5.1 version of stormpath.js.

**Pull request closed without merging**
